# Generated by Django 3.2.5 on 2021-07-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donators',
            fields=[
                ('donatorid', models.AutoField(primary_key=True, serialize=False, verbose_name='donator nr.')),
                ('creator', models.CharField(max_length=12, verbose_name='oprettet af')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='tidspunkt for registrering', verbose_name='oprettet')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='sidst rettet')),
                ('donatorinstitution', models.CharField(blank=True, db_index=True, help_text='hjalp', max_length=255, null=True, verbose_name='firma/institution')),
                ('donatorposition', models.CharField(blank=True, max_length=255, null=True, verbose_name='stilling')),
                ('donatorname', models.CharField(db_index=True, help_text='fornavn(e) efternavn(e)', max_length=255, verbose_name='navn')),
                ('donatoraddress', models.CharField(blank=True, help_text='adresse, postnummer og by', max_length=255, null=True, verbose_name='adresse')),
                ('donatorphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='telefon')),
                ('donatoremail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'donator',
                'verbose_name_plural': 'donatorer',
                'db_table': 'donators',
                'ordering': ['donatorname'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False, verbose_name='sag nr.')),
                ('creator', models.CharField(max_length=12, verbose_name='oprettet af')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='tidspunkt for registrering', verbose_name='oprettet')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='sidst rettet')),
                ('filetitle', models.CharField(max_length=255, null=True, verbose_name='Titel')),
                ('filedescription', models.TextField(blank=True, null=True, verbose_name='beskrivelse')),
                ('datingfrom', models.DateField(null=True, verbose_name='Datering fra')),
                ('datingto', models.DateField(blank=True, null=True, verbose_name='Datering til')),
            ],
            options={
                'verbose_name': 'sag',
                'verbose_name_plural': 'sager',
                'db_table': 'files',
                'ordering': ['filetitle'],
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureid', models.AutoField(primary_key=True, serialize=False, verbose_name='billede nr.')),
                ('picturetext', models.TextField(verbose_name='beskrivelse')),
                ('pictureregisteredby', models.CharField(max_length=12, null=True, verbose_name='oprettet af')),
                ('pictureregistered', models.DateTimeField(auto_now_add=True, verbose_name='registreret')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='rettet')),
                ('pictureoriginal', models.ImageField(help_text='uploadet billede i oprindelig størrelse', upload_to='pictureoriginal', verbose_name='billede')),
                ('picturemedium', models.ImageField(editable=False, upload_to='picturemedium')),
                ('picturelow', models.ImageField(editable=False, upload_to='picturelow')),
            ],
            options={
                'verbose_name': 'billede',
                'verbose_name_plural': 'billeder',
                'db_table': 'pictures_dj',
                'ordering': ['picturetext'],
            },
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('producerid', models.AutoField(primary_key=True, serialize=False, verbose_name='producent nr.')),
                ('creator', models.CharField(max_length=12, verbose_name='oprettet af')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='tidspunkt for registrering', verbose_name='oprettet')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='rettet')),
                ('producertitle', models.CharField(help_text='producent/fabrikant/forfatter', max_length=255, null=True, verbose_name='navn')),
                ('producerdescription', models.TextField(blank=True, null=True, verbose_name='beskrivelse')),
            ],
            options={
                'verbose_name': 'producent',
                'verbose_name_plural': 'producenter',
                'db_table': 'producers',
                'ordering': ['producertitle'],
            },
        ),
        migrations.CreateModel(
            name='Sted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stednavn', models.CharField(blank=True, help_text='område/kommune/bynavn', max_length=60, null=True, verbose_name='stednavn')),
            ],
            options={
                'verbose_name': 'sted',
                'verbose_name_plural': 'steder',
                'db_table': 'sted',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectid', models.AutoField(primary_key=True, serialize=False, verbose_name='emnegruppe nr.')),
                ('creator', models.CharField(max_length=12, verbose_name='oprettet af')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='tidspunkt for registrering', verbose_name='oprettet')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='rettet')),
                ('subjecttitle', models.CharField(max_length=255, null=True, verbose_name='navn')),
                ('subjectdescription', models.TextField(blank=True, null=True, verbose_name='beskrivelse')),
            ],
            options={
                'verbose_name': 'emnegruppe',
                'verbose_name_plural': 'emnegrupper',
                'db_table': 'subjects',
                'ordering': ['subjecttitle'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='genstand nr.')),
                ('itemtemporary', models.IntegerField(blank=True, default=0)),
                ('olditemid', models.CharField(blank=True, max_length=255, verbose_name='gammelt nr.')),
                ('itemdeleted', models.IntegerField(choices=[('publiseret', ((0, 'godkendt'),)), ('redaktion', ((1, 'klar'), (2, 'kladde'))), ('offline', ((3, 'udgået'), (4, 'intern')))], default=0, null=True, verbose_name='status')),
                ('itemheadline', models.CharField(db_index=True, max_length=255, verbose_name='betegnelse')),
                ('itemdescription', models.TextField(blank=True, default='', verbose_name='beskrivelse')),
                ('itemsize', models.CharField(blank=True, max_length=255, verbose_name='størrelse')),
                ('itemweight', models.CharField(blank=True, max_length=255, verbose_name='Vægt')),
                ('itemmodeltype', models.CharField(blank=True, max_length=255, verbose_name='model/type')),
                ('itemserialno', models.CharField(blank=True, max_length=255, verbose_name='serienummer')),
                ('itemdatingfrom', models.DateField(null=True, verbose_name='Datering fra')),
                ('itemdatingto', models.DateField(blank=True, null=True, verbose_name='Datering til')),
                ('itemacquiretype', models.IntegerField(choices=[(0, 'Ukendt'), (1, 'Gave'), (3, 'Køb'), (4, 'Deponering')], default=0, null=True, verbose_name='modtaget som')),
                ('itemdepositeduntil', models.DateField(blank=True, null=True, verbose_name='deponeret/udlånt indtil')),
                ('itemoutdated', models.IntegerField(blank=True, null=True, verbose_name='udgået')),
                ('itemborroweduntil', models.DateField(blank=True, null=True, verbose_name='udlånt indtil')),
                ('itemreceived', models.DateField(blank=True, null=True, verbose_name='modtagelsesdato')),
                ('itemreceivedby', models.CharField(blank=True, max_length=12, verbose_name='modtaget af')),
                ('itemregistered', models.DateField(blank=True, null=True, verbose_name='registreringsdato')),
                ('itemregisteredby', models.CharField(blank=True, max_length=12, null=True, verbose_name='oprettet af')),
                ('lastmodified', models.DateTimeField(auto_now=True, null=True, verbose_name='rettet')),
                ('itemthanksletter', models.DateField(blank=True, null=True, verbose_name='takkebrev afsendt')),
                ('placementid', models.IntegerField(blank=True, null=True, verbose_name='placering')),
                ('itemlocation', models.TextField(blank=True, db_column='itemlocation', null=True, verbose_name='pladsering')),
                ('itemusedby', models.TextField(blank=True, verbose_name='brugt af')),
                ('itemusedfor', models.TextField(blank=True, verbose_name='til hvad')),
                ('itemusedwhere', models.TextField(blank=True, verbose_name='hvor')),
                ('itemusedfrom', models.DateField(blank=True, null=True, verbose_name='brugt fra')),
                ('itemusedto', models.DateField(blank=True, null=True, verbose_name='brugt indtil')),
                ('itemusedendfrom', models.DateField(blank=True, null=True, verbose_name='udgået af brug/nedtaget')),
                ('itemusedendto', models.DateField(blank=True, null=True, verbose_name='udgået af brug/nedtaget')),
                ('itemextrainfo', models.TextField(blank=True, verbose_name='særlige oplysninger')),
                ('itemrestoration', models.TextField(blank=True, verbose_name='restaurering')),
                ('itemreferences', models.TextField(blank=True, verbose_name='litteraturhenvisninger')),
                ('itemremarks', models.TextField(blank=True, help_text='internt brug', verbose_name='bemærkninger')),
                ('iteminternal', models.IntegerField(blank=True, default=0, help_text='forenigens aktiv', verbose_name='intern')),
                ('donatorid', models.ForeignKey(blank=True, db_column='donatorid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ddhf_data.donators', verbose_name='donator')),
                ('fileid', models.ForeignKey(db_column='fileid', on_delete=django.db.models.deletion.CASCADE, to='ddhf_data.files', verbose_name='sag nr.')),
                ('itempicture', models.ManyToManyField(blank=True, null=True, to='ddhf_data.Pictures', verbose_name='billeder')),
                ('itemsubject', models.ManyToManyField(blank=True, null=True, related_name='itemlist', to='ddhf_data.Subjects', verbose_name='emnegrupper')),
                ('itemusedwhereid', models.ForeignKey(blank=True, db_column='itemusedwhereid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ddhf_data.sted', verbose_name='brugt i geografisk område')),
                ('producerid', models.ForeignKey(blank=True, db_column='producerid', help_text='producent/fabrikant/forfatter', null=True, on_delete=django.db.models.deletion.CASCADE, to='ddhf_data.producers', verbose_name='producent')),
            ],
            options={
                'verbose_name': 'genstand',
                'verbose_name_plural': 'genstande',
                'db_table': 'items',
                'ordering': ['itemheadline'],
            },
        ),
    ]
